package parquet.compat.test;

import java.io.File;
import java.io.IOException;

import parquet.Preconditions;
import parquet.Version;


/**
 * This is a utility to generate parquet files for
 * current version of parquet-column. Files generated by this 
 * utility are under $PROJECT_HOME/testdata/tpch/${version}.
 * These files should be checked in to git for 
 * backwards compatibility tests.
 * 
 * @author amokashi
 *
 */
public class ParquetFileGenerationUtil {
  /**
   * 
   * @param args
   * @throws IOException
   */
  public static void main(String[] args) throws IOException {
    final File[] csvFiles = Utils.getAllOriginalCSVFiles();

    String version = Version.VERSION_NUMBER;
    Preconditions.checkNotNull(version, "VERSION_NUMBER");

    for (File csvFile : csvFiles) {
      File parquetVersionedFile = Utils.getParquetVersionedFile(Utils.getFileNamePrefix(csvFile), 
          version, false);
      Utils.convertCsvToParquet(csvFile, parquetVersionedFile);
      System.out.println(parquetVersionedFile.getName());
    }
  }
}
