/**
 * Copyright 2012 Twitter, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package parquet.compat.test;

import java.io.File;
import java.io.IOException;

import parquet.Preconditions;
import parquet.Version;

/**
 * This is a utility to generate parquet files for
 * current version of parquet-column. Files generated by this 
 * utility are under $PROJECT_HOME/testdata/tpch/${version}.
 * These files should be checked in to git for 
 * backwards compatibility tests.
 * 
 * @author amokashi
 *
 */
public class ParquetFileGenerationUtil {
  /**
   * 
   * @param args
   * @throws IOException
   */
  public static void main(String[] args) throws IOException {
    final File[] csvFiles = Utils.getAllOriginalCSVFiles();

    String version = Version.VERSION_NUMBER;
    Preconditions.checkNotNull(version, "VERSION_NUMBER");

    for (File csvFile : csvFiles) {
      File parquetVersionedFile = Utils.getParquetVersionedFile(Utils.getFileNamePrefix(csvFile), 
          version, false);
      ConvertUtils.convertCsvToParquet(csvFile, parquetVersionedFile);
      System.out.println(parquetVersionedFile.getName());
    }
  }
}
